### ISSUE TITLE
Server fails to load up

### ISSUE THREAD

**Issue by ExDrill** [MehVahdJukaar/WIPsuppMULTI#1]
```
[02Aug2022 11:53:03.801] [main/INFO] [net.minecraft.server.MinecraftServer/]: Found new data pack Supplementaries Generated Pack, loading it automatically
[02Aug2022 11:53:03.999] [main/INFO] [net.mehvahdjukaar.supplementaries.Supplementaries/]: Generated runtime SERVER_DATA for pack Supplementaries Generated Pack in: 157 ms
[02Aug2022 11:53:05.719] [Worker-Main-7/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecraft:swamp_hut (from supplementaries-1.19-2.0.8.jar), #minecraft:bastion_remnant (from supplementaries-1.19-2.0.8.jar), #minecraft:jungle_pyramid (from supplementaries-1.19-2.0.8.jar), #minecraft:desert_pyramid (from supplementaries-1.19-2.0.8.jar), #minecraft:pillager_outpost (from supplementaries-1.19-2.0.8.jar), #minecraft:igloo (from supplementaries-1.19-2.0.8.jar), #minecraft:end_city (from supplementaries-1.19-2.0.8.jar), #minecraft:swamp_hut (from supplementaries-1.19-2.0.8.jar), #minecraft:bastion_remnant (from supplementaries-1.19-2.0.8.jar), #minecraft:jungle_pyramid (from supplementaries-1.19-2.0.8.jar), #minecraft:desert_pyramid (from supplementaries-1.19-2.0.8.jar), #minecraft:pillager_outpost (from supplementaries-1.19-2.0.8.jar), #minecraft:igloo (from supplementaries-1.19-2.0.8.jar), #minecraft:end_city (from supplementaries-1.19-2.0.8.jar)] as it is missing following references: #minecraft:swamp_hut (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:bastion_remnant (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:jungle_pyramid (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:desert_pyramid (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:pillager_outpost (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:igloo (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:end_city (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:swamp_hut (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:bastion_remnant (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:jungle_pyramid (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:desert_pyramid (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:pillager_outpost (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:igloo (from supplementaries-1.19-2.0.8.jar), 
	#minecraft:end_city (from supplementaries-1.19-2.0.8.jar)
[02Aug2022 11:53:06.565] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe supplementaries:spiky_bomb as it's serializer returned null
[02Aug2022 11:53:06.571] [main/INFO] [net.minecraft.world.item.crafting.RecipeManager/]: Skipping loading recipe supplementaries:brass_lantern as it's serializer returned null
[02Aug2022 11:53:06.573] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[02Aug2022 11:53:06.574] [main/WARN] [net.minecraft.server.Main/]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:182) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19-41.1.0.jar%2365!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.19-41.1.0.jar%2365!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar%2353!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.mehvahdjukaar.supplementaries.integration.QuarkCompat.isVerticalSlabEnabled(QuarkCompat.java) ~[supplementaries-1.19-2.0.8.jar%23122!/:?]
	at net.mehvahdjukaar.supplementaries.integration.CompatHandler.isVerticalSlabEnabled(CompatHandler.java:118) ~[supplementaries-1.19-2.0.8.jar%23122!/:?]
	at net.mehvahdjukaar.supplementaries.configs.RegistryConfigs.isEnabled(RegistryConfigs.java:35) ~[supplementaries-1.19-2.0.8.jar%23122!/:?]
	at net.mehvahdjukaar.supplementaries.common.items.crafting.forge.OptionalRecipeCondition.test(OptionalRecipeCondition.java:22) ~[supplementaries-1.19-2.0.8.jar%23122!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:214) ~[forge-1.19-41.1.0-universal.jar%23130!/:?]
	at net.minecraftforge.common.crafting.CraftingHelper.processConditions(CraftingHelper.java:203) ~[forge-1.19-41.1.0-universal.jar%23130!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:63) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	at net.minecraft.Util.m_214652_(Util.java:774) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	at net.minecraft.Util.m_214679_(Util.java:763) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	at net.minecraft.server.Main.main(Main.java:157) ~[server-1.19-20220607.102129-srg.jar%23125!/:?]
	... 13 more
```

**Comment by MehVahdJukaar** [comment]
this should have been fixed
